[package]
name = "coatl"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = "0.5.1"
parser = { path = "../parser" }

[dependencies.pyo3]
version = "0.25.0"
features = ["auto-initialize", "abi3-py37"]
